# Numpy Array And Basics

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### LIST vs NUMPY

In [3]:
list=[1,2,3]
arr=np.array([1,2,3])
print(list*3)# adds 3 times the list
print(arr*3)# multiplies the elemjents to array

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [4]:
import time
l=[i*3 for i in range(1000)]
start=time.time()
print('total time required : ',time.time()-start)
start=time.time()
n=np.arange(1000)*3
print('total time required : ',time.time()-start)

total time required :  4.291534423828125e-05
total time required :  0.0014386177062988281


### creating array from scratch


In [5]:
zeros=np.zeros((4,4))
print(zeros)
ones=np.ones((4,4))
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Creating array with pre defined methods of numpy


In [6]:
svn = np.full((3,3),7)#it will create 2x2 array with all elements filled with 7s'
print(svn)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Creating random elements aaray using random method

In [ ]:
arr=np.random.rand(5,5)*100
arr=np.floor(arr)
arr

array([[75., 81., 96., 40., 63.],
       [72.,  3.,  5., 29., 43.],
       [63., 45., 54., 84., 13.],
       [66., 28., 80., 32.,  8.],
       [10., 81., 54., 53., 26.]])

## Vector , Matrix , Tensor

In [8]:
import numpy as np
vector = np.array([1,2,3,4]) 
matrix=np.array([[1,2],[3,4]])
tensor = np.array([
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]
])
print(vector)
print(matrix)
print(tensor)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Array Properties


In [9]:
arr=np.array([[1,2,3],[4,5,23]])*100
print(arr)
print(f'shape : {arr.shape}')# rows x cols
print(f'size : { arr.size}')# total number of elements present in the array
print(f'dimension : { arr.ndim}')# num of rows
print(f'Data type : { arr.dtype}')
t=arr.T# transpose
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a.T
print(b)

[[ 100  200  300]
 [ 400  500 2300]]
shape : (2, 3)
size : 6
dimension : 2
Data type : int64
[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [21]:
import numpy as np
arr=np.arange(16)
brr=arr.reshape((4,4))
print(brr)
crr=brr.flatten()
print(crr)
data=np.random.rand(10,10)*100
data=np.floor(data)
data=data.flatten()
data

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([67.,  7., 33., 96.,  2., 57., 70.,  0., 17., 29., 49.,  7., 37.,
       60., 52., 20., 97., 99., 39., 34., 36., 40., 74., 45., 49., 90.,
       18., 20., 72., 69.,  4., 87., 11., 11., 96., 58., 18., 69., 56.,
       77., 50., 74., 30.,  0., 36., 10., 12., 58., 42., 30., 74., 80.,
       92., 13., 15., 21., 43., 35., 16., 11., 42., 29., 84., 68., 87.,
       27., 11.,  0., 16., 13., 45., 78., 53., 49., 47., 63., 87., 74.,
       70., 72.,  3., 25., 19., 81., 27., 70., 28., 46., 19.,  9., 72.,
        4., 68., 23., 60., 99., 47., 38., 49., 93.])