In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.floor(np.random.rand(5,5)*10)
print(arr2)

[[9. 3. 2. 4. 4.]
 [1. 5. 6. 3. 0.]
 [7. 8. 5. 3. 0.]
 [6. 7. 3. 2. 1.]
 [6. 4. 0. 3. 7.]]


## Saving the array

In [3]:
svd1=np.save('svd1.npy',arr2)
print(svd1)
k=np.load('svd1.npy')
print(k)

None
[[9. 3. 2. 4. 4.]
 [1. 5. 6. 3. 0.]
 [7. 8. 5. 3. 0.]
 [6. 7. 3. 2. 1.]
 [6. 4. 0. 3. 7.]]


# Making dark version of a image

In [4]:
try:
    logo = mpimg.imread('anim.jpg')
    #if file is not on .npy then use imerd to convert it and then do operations 
    arr=np.recarray(logo)
    print(logo)
    plt.figure(figsize=(10,6))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Animesh's Numpy Logo  ")
    plt.grid(False)

    plt.subplot(122)
    plt.title("Dark Mode enabled")
    dark=1-logo
    plt.imshow(dark)
    plt.grid(False)
except Exception as e:
    print('error')

error


In [8]:
for i in range(1):
    for j in range(i):
        print(i,end=' ')
    print()

In [15]:
n=int(input('Enter value : '))
for i in range(n+1):
    for j in range(i):
        print('<>',end=' ')
    print()
for i in range(n+1,0,-1):
    for j in range(i):
        print('<>',end= ' ')
    print()


<> 
<> <> 
<> <> <> 
<> <> <> <> 
<> <> <> <> <> 
<> <> <> <> <> <> 
<> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> <> 
<> <> <> <> <> <> <> 
<> <> <> <> <> <> 
<> <> <> <> <> 
<> <> <> <> 
<> <> <> 
<> <> 
<> 


## while loop

In [17]:
i=0
while i<2:
    print('inside looop')
    i+=1
else:
    print('outed from the loop')

inside looop
inside looop
outed from the loop


In [20]:
d=int(input("Enter a number : "))
i=1
while i<=10:
    print(f'{d}   *   {i}    =   {d*i}\n')
    i+=1

5   *   1    =   5

5   *   2    =   10

5   *   3    =   15

5   *   4    =   20

5   *   5    =   25

5   *   6    =   30

5   *   7    =   35

5   *   8    =   40

5   *   9    =   45

5   *   10    =   50



In [23]:
n=int(input('enter number : '))
cnt=0
if n<2:
    print('Not prime')
elif n==2:
    print('Prime')
else:
    for i in range(2,n-1):
        if n%i==0:
            print(' not prime')
            cnt+=1
            break;
    if cnt==0:
        print('prime')

prime


In [29]:
n=input('enter a string : ')
i=0
j=len(n)-1
k=0
while i<j:
    if n[i]!=n[j]:
        print('Not palindrome')
        k+=1
        break
    else:
        i+=1
        j-=1
 
if k==0:
    print('palindrome')


Not palindrome
