# Numpy Array And Basics

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### LIST vs NUMPY

In [3]:
list=[1,2,3]
arr=np.array([1,2,3])
print(list*3)# adds 3 times the list
print(arr*3)# multiplies the elemjents to array

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [13]:
import time
l=[i*3 for i in range(1000)]
start=time.time()
print('total time required : ',time.time()-start)
start=time.time()
n=np.arange(1000)*3
print('total time required : ',time.time()-start)

total time required :  5.1975250244140625e-05
total time required :  0.00019216537475585938


### creating array from scratch


In [5]:
zeros=np.zeros((4,4))
print(zeros)
ones=np.ones((4,4))
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Creating array with pre defined methods of numpy


In [6]:
svn = np.full((3,3),7)#it will create 2x2 array with all elements filled with 7s'
print(svn)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Creating random elements aaray using random method

In [20]:
import numpy as np
rand_arr=np.random.rand(5,5)*100
print(rand_arr)
florred_arr=np.floor(rand_arr)
print(florred_arr)


[[25.60812828 90.38106207 33.62695372 50.14817601  5.79786969]
 [42.33003276 12.92222149 77.34868631 76.20325126 15.76710165]
 [40.64188226 51.21599999 39.03803369 20.16042319 19.31335124]
 [74.16723567 27.73541663 49.70896876 84.27975147 17.93298634]
 [63.09025173 65.9794772  17.1242399   7.59287269 32.2167347 ]]
[[25. 90. 33. 50.  5.]
 [42. 12. 77. 76. 15.]
 [40. 51. 39. 20. 19.]
 [74. 27. 49. 84. 17.]
 [63. 65. 17.  7. 32.]]


## Vector , Matrix , Tensor

In [8]:
import numpy as np
vector = np.array([1,2,3,4]) 
matrix=np.array([[1,2],[3,4]])
tensor = np.array([
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]
])
print(vector)
print(matrix)
print(tensor)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Array Properties


In [9]:
arr=np.array([[1,2,3],[4,5,23]])*100
print(arr)
print(f'shape : {arr.shape}')# rows x cols
print(f'size : { arr.size}')# total number of elements present in the array
print(f'dimension : { arr.ndim}')# num of rows
print(f'Data type : { arr.dtype}')
t=arr.T# transpose
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a.T
print(b)

[[ 100  200  300]
 [ 400  500 2300]]
shape : (2, 3)
size : 6
dimension : 2
Data type : int64
[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [10]:
import numpy as np
arr=np.arange(16)
brr=arr.reshape((4,4))
print(brr)
crr=brr.flatten()
print(crr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
