# Numpy Array Operations


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(f'main array : {arr1}')
print(f'sliced array : {arr1[1:7]}')
print(f'with steps : {arr1[1:8:3]}')
print(f'neg indexing : {arr1[::-1]}')


main array : [1 2 3 4 5 6 7 8 9]
sliced array : [2 3 4 5 6 7]
with steps : [2 5 8]
neg indexing : [9 8 7 6 5 4 3 2 1]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(arr)
# print(f'sliced array : {arr[1:7]}')
# print(f'neg indexing : {arr[::-1]}')
# print(arr[1,1])
# print(arr[1])# it will print the 1st row
print(arr[:,2])# print the 2nd col of each row

[3 6 9]


## Sorting


In [ ]:
unsorted = np.array([9,8,7,6,5,4,3,2,1])
sorted = np.sort(unsorted)
print(sorted)

arr_unsorted = np.array([[10,2,3],[3,2,1],[3,2,1]]) 
print(np.sort(arr_unsorted,axis=1))

# axis = 0 , sort on col
#axis = 1 , sort on row


[1 2 3 4 5 6 7 8 9]
[[ 2  3 10]
 [ 1  2  3]
 [ 1  2  3]]


## Filter


In [5]:
arr = np.array([9,8,7,6,5,4,3,2,1])
mask = arr%2==0
even = arr[mask]# mask filters the data
print(even)


[8 6 4 2]


## Fancy indexing and where

In [ ]:
arr = np.sort(np.array([9,8,7,6,5,4,3,2,1]))
# print(arr) 
indices = [ 0,1,2,3]
print(arr[indices])
print('np where :',arr[np.where((arr>4) & (arr%2==0))])

[1 2 3 4]
np where : [6 8]


In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9])
a1 = np.where(arr>5 , arr*10 ,arr ) #( condition , true , false)
print(a1)
# if arr>5:
#     arr*10
# else:
#     arr


[ 1  2  3  4  5 60 70 80 90]


## Adding and Removing data

In [8]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8,5])
# print(arr1 + arr2)#(Shape must be same)
combined = np.concat((arr1,arr2))
print(combined)
print(arr1.shape == arr2.shape)

[1 2 3 4 5 6 7 8 5]
False


In [ ]:
arr1=np.array([[1,2,3],[4,5,6],])
# x=np.concatenate((arr1,arr2),axis=0)
# print(x)
arr2=np.array([[2,2,2]])
comb = np.vstack((arr1,arr2))
print(comb)
arr2=np.array([[2],[2]])# for column
comb = np.hstack((arr1,arr2))
print(comb)

[[1 2 3]
 [4 5 6]
 [2 2 2]]
[[1 2 3 2]
 [4 5 6 2]]


## Delete Operation

In [10]:
arr=np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr,2)
print(deleted)

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.delete(arr,0,axis=0)) # delete 0th column
#   output is [[2 3]
#             [5 6]
#             [8 9]]
print(np.delete(arr,0,axis=1)) # delete 0th row
# output is 
# [[4 5 6]
#  [7 8 9]]


[1 2 4 5 6 7]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
