In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.floor(np.random.rand(5,5)*10)
print(arr2)

[[6. 6. 0. 5. 5.]
 [4. 1. 9. 3. 7.]
 [3. 5. 6. 0. 9.]
 [1. 3. 1. 7. 7.]
 [0. 9. 6. 4. 0.]]


## Saving the array

In [3]:
svd1=np.save('svd1.npy',arr2)
print(svd1)
k=np.load('svd1.npy')
print(k)

None
[[6. 6. 0. 5. 5.]
 [4. 1. 9. 3. 7.]
 [3. 5. 6. 0. 9.]
 [1. 3. 1. 7. 7.]
 [0. 9. 6. 4. 0.]]


# Making dark version of a image

In [4]:
try:
    logo = mpimg.imread('anim.jpg')
    #if file is not on .npy then use imerd to convert it and then do operations 
    arr=np.recarray(logo)
    print(logo)
    plt.figure(figsize=(10,6))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Animesh's Numpy Logo  ")
    plt.grid(False)

    plt.subplot(122)
    plt.title("Dark Mode enabled")
    dark=1-logo
    plt.imshow(dark)
    plt.grid(False)
except Exception as e:
    print('error')

error
